apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: share-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: alfresco-content-services
      app.kubernetes.io/name: share