apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alfresco-content-services-share
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: alfresco-content-services-share-hmpps-delius-alfresco-prod-green
    nginx.ingress.kubernetes.io/whitelist-source-range: "placeholder"
spec:
  rules:
    - host: share.hmpps-delius-alfresco-prod.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - backend:
              service:
                name: alfresco-content-services-share
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: alfresco-content-services-share
                port:
                  number: 80
            path: /share/page/
            pathType: Prefix
    - host: share.alfresco.hmpps.service.justice.gov.uk
      http:
        paths:
          - backend:
              service:
                name: alfresco-content-services-share
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: alfresco-content-services-share
                port:
                  number: 80
            path: /share/page/
            pathType: Prefix
  tls:
    - hosts:
        - share.hmpps-delius-alfresco-prod.apps.live.cloud-platform.service.justice.gov.uk
        - share.alfresco.hmpps.service.justice.gov.uk
      secretName: share-ingress-cert
